# Generated by Django 5.0.7 on 2025-03-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlocation',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlocation',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
