# Generated by Django 5.0.7 on 2025-03-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productlocation_latitude_productlocation_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='featured_product',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
