# Generated by Django 5.0.7 on 2025-03-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
    ]
