# Generated by Django 5.0.7 on 2025-04-07 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='branches', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.branch'),
            preserve_default=False,
        ),
    ]
