# Generated by Django 5.0.7 on 2025-04-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_branch_categories_product_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='branches',
            field=models.ManyToManyField(to='products.branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='categories',
            field=models.ManyToManyField(to='products.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
