# Generated by Django 5.0.7 on 2025-04-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_branches_alter_branch_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='branches',
        ),
    ]
