# Generated by Django 5.0.7 on 2025-04-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_category_delete_productdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='rating',
        ),
    ]
