# Generated by Django 5.0.7 on 2025-03-12 10:45

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Full Name', max_length=50)),
                ('subject', models.CharField(help_text='Message Subject', max_length=100)),
                ('message', models.TextField(help_text='Your Message', max_length=1000)),
                ('email', models.EmailField(help_text='Your Email Address', max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Your Contact Number', max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Gallery Images', null=True, upload_to='gallery/images')),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.CharField(default='Mandian Abbottabad Near Comsats University', help_text='office address', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_email1',
            field=models.EmailField(default='support@zaalasociety.com', help_text='Application contact email 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_email2',
            field=models.EmailField(default='support@zaalasociety.com', help_text='Application contact email 2', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_phone1',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+923029677678', help_text='Application contact phone 1', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_phone2',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+923065953957', help_text='Application contact phone 2', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(default='will be update it soon', help_text='Application description'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(default='Zaala Society', help_text='Application name', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='short_name',
            field=models.CharField(default='ZS', help_text='Your application short name', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='tagline',
            field=models.CharField(default='will be update it soon', help_text='Your application business line', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='terms_url',
            field=models.URLField(default='https://zaalasociety.com/terms-of-use/', help_text='Terms and Conditions page link', max_length=255),
        ),
    ]
