# Generated by Django 5.0.7 on 2025-04-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
